questions_data = [
    ('1) Who developed Python Programming Language?',
     ['Wick van Rossum', 'Rasmus Lerdorf', 'Guido van Rossum', 'Niene Stom'],
     3),
    ('2) Which type of Programming does Python support?',
     ['object-oriented programming', 'structured programming', 'functional programming', 'all of the mentioned'],
     4),
    ('3) Is Python case sensitive when dealing with identifiers?',
     ['no', 'yes', 'machine dependent', 'none of the mentioned'],
     2),
    ('4) Which of the following is the correct extension of the Python file?',
     ['.python', '.pl', '.py', '.p'],
     3),
    ('5) Is Python code compiled or interpreted?',
     ['Python code is both compiled and interpreted', 'Python code is neither compiled nor interpreted',
      'Python code is only compiled', 'Python code is only interpreted'],
     1),
    ('6) All keywords in Python are in _________',
     ['Capitalized', 'lower case', 'UPPER CASE', 'None of the mentioned'],
     4),
    ('7) What will be the value of the following Python expression? 4 + 3 % 5',
     ['7', '2', '4', '1'],
     1),
    ('8) Which of the following is used to define a block of code in Python language?',
     ['Indentation', 'Key', 'Brackets', 'All of the mentioned'],
     1),
    ('9) Which keyword is used for function in Python language?',
     ['Function', 'def', 'Fun', 'Define'],
     2),
    ('10) Which of the following character is used to give single-line comments in Python?',
     ['//', '#', '!', '/*'],
     2)
]